apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-ramzi
  namespace: ramzi
  labels:
    type: local
spec:
  storageClassName: csi-cinder-high-speed
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
