# Define 'Service' to expose FrontEnd Application
apiVersion: v1
kind: Service
metadata:
  name: to-do-app-frontend
spec:
  type: LoadBalancer
  selector:
    app: to-do-app-frontend
  ports:
    - port: 80
      targetPort: 4200
        #nodePort: 4200
---
# 'Deployment' to manage of configuration of frontEnd Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app-frontend
  labels: # pod labels should match these
    app: to-do-app-frontend
    tier: frontend
spec:
  replicas: 1  # number of replicas of frontEnd application
  selector:
    matchLabels:
      app: to-do-app
      tier: frontend
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' labels
        app: to-do-app
        tier: frontend
    spec:
      containers:
      - name: to-do-app-frontend
        image: salimbechraoui25/frontend:1.0 # docker image of frontend application
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: backend-url
              key: URL
        ports:
        - containerPort: 80
