apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    tier: database
    service: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
      service: mysqldb
#  strategy:
#    type: Recreate
  template:
    metadata:
      name: mysqldb
      labels:
        app: mysqldb
        tier: database
#        network/wedonetwork: "true"
        service: mysqldb
    spec:
      containers:
      - image: mysql:8 # image from docker-hub
        name: mysqldb
        imagePullPolicy: "IfNotPresent"
#        args:
#          - "--ignore-db-dir=lost+found"
        resources: {}
        env:
        - name: MYSQL_ROOT_PASSWORD # Setting Root Password of mysql From a 'Secret'
#          value: salimbackend
          valueFrom:
            secretKeyRef:
              name: db-root-credentials
              key: password
        
        - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
#          value: springboot
          valueFrom:
            configMapKeyRef:
              name: db-conf
              key: name

        ports:
        - containerPort: 3306
          name: mysqldb
        volumeMounts:        # Mounting voulume obtained from Persistent Volume Claim
        - name: mysql-persistent-storage-salim
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-salim # Obtaining 'vloume' from PVC
        persistentVolumeClaim:
          claimName: mysql-pv-claim-salim
      restartPolicy: Always
status: {}
---
